config/routes.rb
Rails.application.routes.draw do
  
  resources :wikis, only: [:index, :show, :new, :edit, :create, :update, :destroy]
  
  resources :wikis, only: [] do
    resources :collaborators, only: [:new, :create, :destroy]
  end
  
  resources :charges, only: [:new, :create]
  
  devise_for :users

  get 'about' => 'welcome#about'
  get 'downgrade_charge' => 'charges#downgrade'
  
  root 'welcome#index'

end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
    belongs_to :user
    belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :wikis
  has_many :collaborators
  has_many :shared_wikis, through: :collaborators, source: :wiki
  
  after_initialize { self.role ||= :standard }
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
         
  
  enum role: [:standard, :admin, :premium]
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  
  has_many :collaborators
  has_many :users, through: :collaborators
  
  scope :visible_to, -> (user) { user ? all : where(private: false) }
  default_scope { order('created_at DESC') }
  
  def collaborator_for(user)
    collaborators.find_by(user_id: user.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  include Pundit
  
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  
  private
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end
  
  def upgrade_to_premium
    current_user.update_attributes(:role => "premium")
  end
  
  def downgrade_to_standard
    current_user.update_attributes(:role => "standard")
    current_user.wikis.each do |pub|
      pub.update_attributes(private: false)
    end
  end
  
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
    
    def create
    @amount = 15_00
   # Creates a Stripe Customer object, for associating
   # with the charge
   customer = Stripe::Customer.create(
     email: current_user.email,
     card: params[:stripeToken]
   )
 
   # Where the real magic happens
   charge = Stripe::Charge.create(
     customer: customer.id, # Note -- this is NOT the user_id in your app
     amount: @amount,
     description: "Premium Membership - #{current_user.email}",
     currency: 'usd'
   )

   upgrade_to_premium

   flash[:notice] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
   redirect_to root_path # or wherever
 
   # Stripe will send back CardErrors, with friendly messages
   # when something goes wrong.
   # This `rescue block` catches and displays those errors.
   rescue Stripe::CardError => e
     flash[:alert] = e.message
     redirect_to new_charge_path
   end

   def new
   @stripe_btn_data = {
     key: "#{ Rails.configuration.stripe[:publishable_key] }",
     description: "Premium Membership - #{current_user.email}",
     amount: @amount
   }
   end
   
   def downgrade
       downgrade_to_standard
       redirect_to root_path
   end
       
   
 end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  before_action :set_wiki
  
 def new
      @collaborator  = Collaborator.new
      @collaborators = Collaborator.all
      
      @wiki = Wiki.find(params[:wiki_id])
      
      @collaborating_users   = @wiki.collaborators.map { |colab| colab.user }           
      @current_collaborators = @wiki.collaborators
      
      @users_currently_not_collaborating = User.where.not(id: @collaborating_users.map {|user| user.id})
      @currently_not_collaborators = Collaborator.where.not(id: @current_collaborators.map {|colab| colab.id}) 
      
  end
  
  def index
    @users = User.all
  end

  def create
    @collaborator = @wiki.collaborators.new(user_id: params[:user_id])
    if @collaborator.save
      flash[:notice] = "You have added #{@collaborator.user.email} to participate on this wiki."
    else
      flash[:error] = "The collaborator could not be added. Try again."
    end
    redirect_to new_wiki_collaborator_path(@wiki)
  end

  def destroy
    @collaborator = Collaborator.find(params[:id])
    if @collaborator.destroy
      flash[:notice] = "#{@collaborator} was removed and can no longer particiate on this wiki."
    else
      flash[:error] = "Error removing #{@collaborator}, try again."
    end
    redirect_to new_wiki_collaborator_path
  end

  private

  def set_wiki
    @wiki = Wiki.find(params[:wiki_id])
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
  end

  def new
    @wiki = Wiki.new
    @wiki.user = current_user
  end
  
  def create
     @wiki = Wiki.new
     @wiki.title = params[:wiki][:title]
     @wiki.body = params[:wiki][:body]
     @wiki.user = current_user
     @wiki.private = params[:wiki][:private]

     if @wiki.save
       flash[:notice] = "wiki was saved."
       redirect_to @wiki
     else
       flash.now[:alert] = "There was an error saving the wiki. Please try again."
       render :new
     end
  end

  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
  end
  
  def update 
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    @wiki.title = params[:wiki][:title]
    @wiki.body = params[:wiki][:body]
    @wiki.private = params[:wiki][:private]
    @wiki.user = current_user
    
    if @wiki.save
       flash[:notice] = "Wiki was updated."
       redirect_to @wiki
     else
       flash.now[:alert] = "There was an error saving the wiki. Please try again."
       render :edit
    end
  end
  
  def destroy
    @wiki = Wiki.find(params[:id])
    
    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
       redirect_to wikis_path
     else
       flash.now[:alert] = "There was an error deleting the wiki."
       render :show
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/collaborators_helper.rb
module CollaboratorsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
    def markdown(text)
        
        options = {
            filter_html:    true,
            hard_wrap:      true,
            link_attributes: { rel: 'nofollow', target: '_blank'},
            space_after_headers: true,
            fenced_code_blocks: true
        }
        
        extensions = {
            autolink:       true,
            superscript:    true,
            disable_indented_code_blocks: true
        }
        
        renderer = Redcarpet::Render::HTML.new(options)
        markdown = Redcarpet::Markdown.new(renderer, extensions)
        
        markdown.render(text).html_safe
    end
    
    def texterize(markdown)
        sanitize(markdown, tags: %w() ).truncate(150, separator: '/\s/')
    end
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
<% if current_user.role == "standard" %>
   <h4>Gain access to private wikis for only $15.00</h4>
   <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
 <% else %>
 <h4>Are you sure you want to revert from premium back to standard?</h4>
      <%= link_to "Cancel Premium", downgrade_charge_path, class: "btn btn-danger" %>
   <% end %>
 <% end %>

app/views/collaborators/new.html.erb
<div class="container">
 <div class='jumbotron'>
  <h1>Manange colaborators for <%= @wiki.title %></h1>
 
  <div class="row">
    <div class="col-md-6">
       <h3>Add Collaborators</h3>
       <% @users_currently_not_collaborating.each do |user| %>
       <div class="media">
         <div class="media-body">
           <h4 class="media-heading">
             <%= button_to "#{user.email}", {controller: "collaborators", action: "create", wiki_id: @wiki.id, user_id: user.id} , class: 'btn' %>  
            </h4>
         </div>
       </div>
       <% end %>
    </div>
    <div class="col-md-6">
       <h3>Current Collaborators</h3>
         <% @collaborating_users.each do |user| %>
         <div class="media">
           <div class="media-body">
             <h4 class="media-heading">
               <%= button_to "#{user.email}", [@wiki, @current_collaborators.find_by(user_id: user.id)], method: :delete, class: 'btn', data: { confirm: 'Are you sure you want to remove this colaborator?' } %>
             </h4>
           </div>
         </div>
         <% end %>
    </div>
  </div>
 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blocipedia</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% if user_signed_in? %>
   Signed in as: <%= link_to current_user.email, edit_user_registration_path, :class => 'navbar-link' %>
    (<%= link_to current_user.role, new_charge_path, class: "navbar-link"%>)
   - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
   
 <% else %>
   <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> -
   <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
 <% end %>
 - <%= link_to "Home", root_path, :class => 'navbar-link' %>
 - <%= link_to "Wikis", wikis_path(@wikis), :class => 'navbar-link' %>
 

<%= yield %>

</body>
</html>

app/views/welcome/about.html.erb
<h1>Welcome#about</h1>
<p>Find me in app/views/welcome/about.html.erb</p>

app/views/welcome/index.html.erb
<h1>Blocipedia: Social, Markdown Wikis</h1>
<div class="container">
    <div class="jumbotron">
        <h3>Create and view Wikis!</h3>
        <p>Welcome to Blocipedia!</p>
        <div class="row">
            <div class="col">
            <button><%= link_to "New Wiki", new_wiki_path(@wikis), class: 'btn' %> </button>
            </div>
            <div class="col">
            <button><%= link_to "View Wikis", wikis_path(@wikis), class: 'btn' %></button>
            </div>
        </div>
    </div>
</div>

app/views/wikis/_form.html.erb
<% if current_user.admin? || current_user.premium? %>
  <div class="form-group">
    <%= f.label :private, class: 'checkbox' do %>
      <%= f.check_box :private %> Private wiki
    <% end %>
  </div>
<% end %>

app/views/wikis/edit.html.erb
<div class='container'>
       <div class='jumbotron'>
       <%= form_for @wiki do |f| %>
              <div class="form-group">
                <%= f.label :title %>
                <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
              </div>
              <div class="form-group">
                <%= f.label :body %>
                <%= f.text_area :body, rows: 20, class: 'form-control', placeholder: "Enter wiki body" %>
              </div>
              <%= render partial: 'wikis/form', locals: { f: f } %>
                <%= f.submit "Save", class: 'btn' %>
              </div>
       <% end %>
       </div>
</div>

app/views/wikis/index.html.erb
<div class="container-fluid">
<div class='row'>
    <div class='col'>
        <div class="jumbotron">
         <h1>Wikis <button><%= link_to "New Wiki", new_wiki_path(@wiki), class: 'btn' %></button></h1>
            <% @wikis.each do |wiki| %>
                <div class="row">
                  <div class="col-md-8">
                    <h4 class="media-heading">
                      <%= link_to wiki.title, wiki_path(wiki.id) %>
                    </h4>
                  </div>
                  <div class="col-md-4">
                   <%= link_to "Edit", edit_wiki_path(wiki.id), class: 'btn' %>
                   <%= link_to "Delete Wiki", wiki, method: :delete, class: 'btn', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
                  </div>
                </div>
            <% end %>
         </div>
    </div>
 </div>
</div>

app/views/wikis/new.html.erb
<div class='container'>
       <div class='jumbotron'>
        <%= form_for @wiki do |f| %>
            <div class="form-group">
              <%= f.label :title %>
              <%= f.text_field :title, class: 'form-control' %>
           </div>
           <div class="form-group">   
              <%= f.label :body %>
              <%= f.text_area :body, rows: 20, class: 'form-control' %>
           </div>
           <%= render partial: 'wikis/form', locals: { f: f } %>
              <%= f.submit "Save" %>
           </div>
         <% end %>
</div>

app/views/wikis/show.html.erb
<div class="container">
 <div class='jumbotron'>
  <h1><%= @wiki.title %></h1>
 
  <div class="row">
    <div class="col">
      <p><%= markdown(@wiki.body) %></p>
      <small>last edited <%= time_ago_in_words(@wiki.updated_at) %> ago by <%= @wiki.user.email %></small>
      <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn' %>
      <% if @wiki.user == current_user %>
          <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
          <%= link_to "Collaborate", new_wiki_collaborator_path(@wiki), class: 'btn' %>
      <% end %>
    </div>
    </div>
 </div>
 </div>